[package]
name = "smash_script"
version = "0.1.0"
authors = ["blujay <the.blu.dev@gmail.com>"]
edition = "2018"

[dependencies]
skyline = { path = "../skyline-rs" }
skyline_smash = { path = "../skyline-smash" }
lua_macro = { path = "./lua-macro" }