[package]
name = "smash_script"
version = "0.1.0"
authors = ["blujay <the.blu.dev@gmail.com>"]
edition = "2018"

[dependencies]
skyline = { git = "https://github.com/ultimate-research/skyline-rs" }
<<<<<<< HEAD
skyline_smash = { git = "https://github.com/blu-dev/skyline-smash", branch = "l2c_change" }
# skyline = { path = "../skyline-rs" }
# skyline_smash = { path = "../skyline-smash" }
=======
skyline_smash = { git = "https://github.com/ultimate-research/skyline-smash", features = ["weak_l2cvalue"] }
>>>>>>> 5188110459ff302098f0bbf6b96ddad317e4dbef
lua_macro = { path = "./lua-macro" }
num-traits = "0.2.14"